DROP TABLE IF EXISTS customers_raw;
CREATE TABLE customers_raw (
    id INT,
    year_birth INT,
    education VARCHAR(50),
    marital_status VARCHAR(50),
    income NUMERIC,
    kidhome INT,
    teenhome INT,
    dt_customer DATE,
    recency INT,
    mntwines NUMERIC,
    mntfruits NUMERIC,
    mntmeatproducts NUMERIC,
    mntfishproducts NUMERIC,
    mntsweetproducts NUMERIC,
    mntgoldprods NUMERIC,
    numdealspurchases INT,
    numwebpurchases INT,
    numcatalogpurchases INT,
    numstorepurchases INT,
    numwebvisitsmonth INT,
    acceptedcmp3 INT,
    acceptedcmp4 INT,
    acceptedcmp5 INT,
    acceptedcmp1 INT,
    acceptedcmp2 INT,
    complain INT,
    z_costcontact INT,
    z_revenue INT,
    response INT
);
